### ISSUE TITLE
Shall PiFM be listed?

### ISSUE THREAD

**Issue by vi** [thibmaek/awesome-raspberrypi#28]
http://www.icrobotics.co.uk/wiki/index.php/Turning_the_Raspberry_Pi_Into_an_FM_Transmitter

**Comment by thibmaek** [comment]
Sure you can add it in under the Projects. Only thing concerning me (AFAIK Python) is that this wiki mentions PiFM as a Python library but doesn't link back to it anywhere. Is this a native Python library/API? If not please link to a better article linking back to this library.

**Comment by vi** [comment]
Python? I though pifm is a C program. I've tried it on my Pi (on a pre-supplied input file) and it worked.

**Comment by thibmaek** [comment]
Doens't really matter what language it is though. Is it's not a native API/library just try and find a better link than this, if it is in fact a native API/library then feel free to submit a pr for this!
