### ISSUE TITLE
"Limelight" -> "Moonlight"

### ISSUE THREAD

**Issue by raidancampbell** [thibmaek/awesome-raspberrypi#30]
At the request of Limelight Networks, the Nvidia GameStream client formerly known as Limelight was renamed Moonlight a while ago.  The link in the article correctly reroutes to the proper github repo, but references to it being called "limelight" has proven confusing for some users.

I'd suggest directly linking to irtimmer's Moonlight-Embedded repo [here](https://github.com/irtimmer/moonlight-embedded/wiki/Packages).  That is what the [official Moonlight page links](http://moonlight-stream.com/)

**Comment by thibmaek** [comment]
Thanks I'll edit this right away!
